/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgents"];
        put?: never;
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agentId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasksOfAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgent"];
        put: operations["updateAgent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["models"];
        put: operations["classify"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/project-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projectTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["models_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phases/{phaseId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approvePhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phases/{phaseId}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read"];
        put: operations["write"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["plan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/plan/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/plan/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["handoff_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/plan/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["configure"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scaffold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasksOfProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["suggest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/software": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/software/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/software/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/software/{key}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["icon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/software/{key}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["launch_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTasks"];
        put?: never;
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTask"];
        put: operations["updateTask"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assignToAgent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/agent-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suggestionsFor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["handoffs"];
        put?: never;
        post: operations["handoff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/orchestration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["decide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assignToProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reviews"];
        put?: never;
        post: operations["review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["runsOfTask"];
        put?: never;
        post: operations["launch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage/plans/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["anchor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/default-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["defaultFolder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentChoice: {
            /** Format: int64 */
            agentId?: number;
            assigned?: boolean;
            model?: string;
            name?: string;
            reason?: string;
            role?: string;
        };
        AgentCreateRequest: {
            model?: string;
            name: string;
            role: string;
            specialization: string;
        };
        AgentResponse: {
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            id?: number;
            model?: string;
            name?: string;
            role?: string;
            specialization?: string;
            status?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AgentUpdateRequest: {
            model?: string;
            name: string;
            role: string;
            specialization: string;
        };
        ContextFile: {
            exists?: boolean;
            path?: string;
            why?: string;
        };
        Document: {
            /** Format: date-time */
            modified?: string;
            path?: string;
            /** Format: int64 */
            size?: number;
        };
        DocumentWrite: {
            content: string;
        };
        Documents: {
            agents?: components["schemas"]["Document"];
            exists?: boolean;
            handoffs?: components["schemas"]["Document"][];
            implementationPlan?: components["schemas"]["Document"];
            masterPrompt?: components["schemas"]["Document"];
            masterPromptIsTemplate?: boolean;
            phases?: components["schemas"]["Document"][];
            planJson?: components["schemas"]["Document"];
            references?: components["schemas"]["Document"][];
            tasks?: components["schemas"]["Document"][];
            workspacePath?: string;
        };
        GenerateRequest: {
            model?: string;
        };
        HandoffRequest: {
            target: string;
        };
        HandoffResponse: {
            command?: string;
            /** Format: date-time */
            createdAt?: string;
            documentPath?: string;
            /** Format: int64 */
            id?: number;
            prompt?: string;
            requestedBy?: string;
            target?: string;
            /** Format: int64 */
            taskId?: number;
        };
        HandoffResult: {
            handoff?: components["schemas"]["HandoffResponse"];
            prompt?: string;
            promptToClipboard?: boolean;
            task?: components["schemas"]["TaskResponse"];
        };
        LaunchRequest: {
            /** Format: int64 */
            projectId?: number;
        };
        LaunchResponse: {
            command?: string[];
            folderOpened?: boolean;
            key?: string;
            workingDirectory?: string;
        };
        ModelCatalogResponse: {
            engineDefault?: string;
            engineReachable?: boolean;
            models?: components["schemas"]["ModelResponse"][];
            uncatalogued?: components["schemas"]["UncataloguedModel"][];
        };
        ModelChoice: {
            available?: boolean;
            model?: string;
            reason?: string;
            role?: string;
        };
        ModelClassificationRequest: {
            /** @enum {string} */
            lifecycle: "ACTIVE" | "CANDIDATE" | "DEPRECATED" | "RETIRED";
            notes?: string;
            replacedBy?: string;
            /** @enum {string} */
            role: "FAST" | "GENERAL" | "CODER" | "PLANNER" | "VISION" | "REASONING" | "PREMIUM" | "EMBEDDING" | "TEST";
        };
        ModelInfo: {
            available?: boolean;
            billed?: boolean;
            detail?: string;
            id?: string;
            provider?: string;
        };
        ModelList: {
            defaultModel?: string;
            models?: components["schemas"]["ModelInfo"][];
        };
        ModelResponse: {
            capabilities?: string[];
            /** Format: int32 */
            contextWindow?: number;
            displayName?: string;
            engineAvailable?: boolean;
            engineDetail?: string;
            key?: string;
            /** @enum {string} */
            lifecycle?: "ACTIVE" | "CANDIDATE" | "DEPRECATED" | "RETIRED";
            notes?: string;
            parameters?: string;
            providerKey?: string;
            replacedBy?: string;
            /** @enum {string} */
            role?: "FAST" | "GENERAL" | "CODER" | "PLANNER" | "VISION" | "REASONING" | "PREMIUM" | "EMBEDDING" | "TEST";
            sizeGb?: number;
            /** Format: int64 */
            version?: number;
        };
        ModelTokens: {
            model?: string;
            /** Format: int64 */
            tokens?: number;
        };
        Orchestration: {
            agent?: components["schemas"]["AgentChoice"];
            /** @enum {string} */
            autonomyLevel?: "GUIDED" | "SUPERVISED" | "DELEGATED" | "FINAL_REVIEW";
            autonomyRules?: string;
            blockers?: string[];
            code?: string;
            context?: components["schemas"]["ContextFile"][];
            model?: components["schemas"]["ModelChoice"];
            phaseApproved?: boolean;
            /** Format: int64 */
            phaseId?: number;
            /** Format: int32 */
            phaseNumber?: number;
            phaseTitle?: string;
            /** Format: int64 */
            projectId?: number;
            projectName?: string;
            prompt?: string;
            software?: components["schemas"]["SoftwareChoice"][];
            /** @enum {string} */
            status?: "OPEN" | "IN_PROGRESS" | "DONE";
            targets?: components["schemas"]["Target"][];
            /** Format: int64 */
            taskId?: number;
            title?: string;
        };
        PhaseResponse: {
            /** @enum {string} */
            approval?: "PENDING" | "APPROVED" | "CHANGES_REQUESTED";
            approvalNote?: string;
            /** Format: date-time */
            approvedAt?: string;
            documentPath?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            number?: number;
            objective?: string;
            /** Format: int64 */
            projectId?: number;
            /** @enum {string} */
            status?: "PLANNED" | "IN_PROGRESS" | "DONE";
            tasks?: components["schemas"]["TaskResponse"][];
            title?: string;
            /** Format: int64 */
            version?: number;
        };
        PlanResponse: {
            phases?: components["schemas"]["PhaseResponse"][];
            project?: components["schemas"]["ProjectResponse"];
            runs?: components["schemas"]["PlanRunResponse"][];
        };
        PlanRunResponse: {
            /** Format: date-time */
            createdAt?: string;
            failureDetail?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            inputTokens?: number;
            output?: string;
            /** Format: int32 */
            outputTokens?: number;
            /** Format: int32 */
            phases?: number;
            /** Format: int64 */
            projectId?: number;
            requestedBy?: string;
            requestedModel?: string;
            servedModel?: string;
            /** @enum {string} */
            source?: "ENGINE" | "IMPORT";
            /** @enum {string} */
            status?: "RUNNING" | "SUCCEEDED" | "FAILED";
            /** Format: int32 */
            tasks?: number;
        };
        ProfileRequest: {
            /** @enum {string} */
            autonomyLevel?: "GUIDED" | "SUPERVISED" | "DELEGATED" | "FINAL_REVIEW";
            /** @enum {string} */
            projectType?: "WEB_APP" | "BACKEND" | "MOBILE" | "DESKTOP" | "AI_ML" | "GAME" | "THREE_D" | "DATA" | "AUTOMATION" | "API" | "FULL_STACK" | "OTHER";
            stack?: string;
            workspacePath?: string;
        };
        ProjectCreateRequest: {
            description?: string;
            name: string;
        };
        ProjectResponse: {
            /** @enum {string} */
            autonomyLevel?: "GUIDED" | "SUPERVISED" | "DELEGATED" | "FINAL_REVIEW";
            /** Format: date-time */
            createdAt?: string;
            description?: string;
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            planStatus?: "NONE" | "DRAFT" | "APPROVED";
            /** @enum {string} */
            projectType?: "WEB_APP" | "BACKEND" | "MOBILE" | "DESKTOP" | "AI_ML" | "GAME" | "THREE_D" | "DATA" | "AUTOMATION" | "API" | "FULL_STACK" | "OTHER";
            stack?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED";
            /** Format: date-time */
            updatedAt?: string;
            workspacePath?: string;
        };
        ProjectTypeInfo: {
            agentRoles?: string[];
            description?: string;
            label?: string;
            software?: string[];
            stack?: string[];
            /** @enum {string} */
            type?: "WEB_APP" | "BACKEND" | "MOBILE" | "DESKTOP" | "AI_ML" | "GAME" | "THREE_D" | "DATA" | "AUTOMATION" | "API" | "FULL_STACK" | "OTHER";
        };
        ProjectUpdateRequest: {
            description?: string;
            name: string;
        };
        ProviderResponse: {
            baseUrl?: string;
            /** @enum {string} */
            billing?: "FREE" | "PAY_PER_TOKEN" | "SUBSCRIPTION";
            docsUrl?: string;
            engineProvider?: string;
            key?: string;
            /** @enum {string} */
            kind?: "LOCAL" | "CLOUD_API" | "ROUTER" | "SUBSCRIPTION" | "TEST";
            name?: string;
            notes?: string;
            /** @enum {string} */
            status?: "ENABLED" | "DISABLED" | "INCOMPATIBLE_HARDWARE";
        };
        QuotaAnchorRequest: {
            limitNote?: string;
            resetTime?: string;
            /** Format: int32 */
            resetWeekday?: number;
            resetZone?: string;
        };
        ReviewRequest: {
            /** Format: int64 */
            handoffId?: number;
            note?: string;
            /** Format: int64 */
            runId?: number;
            /** @enum {string} */
            verdict: "ACCEPTED" | "CHANGES_REQUESTED";
        };
        ReviewResponse: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            handoffId?: number;
            /** Format: int64 */
            id?: number;
            note?: string;
            reviewer?: string;
            /** Format: int64 */
            runId?: number;
            /** Format: int64 */
            taskId?: number;
            /** @enum {string} */
            verdict?: "ACCEPTED" | "CHANGES_REQUESTED";
        };
        ReviewResult: {
            review?: components["schemas"]["ReviewResponse"];
            task?: components["schemas"]["TaskResponse"];
        };
        RoutingRequest: {
            text: string;
        };
        RunCreateRequest: {
            model?: string;
        };
        RunResponse: {
            /** Format: int64 */
            agentId?: number;
            correlationId?: string;
            /** Format: date-time */
            createdAt?: string;
            failureDetail?: string;
            failureType?: string;
            finishReason?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            inputTokens?: number;
            /** Format: int64 */
            latencyMs?: number;
            output?: string;
            /** Format: int32 */
            outputTokens?: number;
            requestedBy?: string;
            requestedModel?: string;
            servedModel?: string;
            /** Format: date-time */
            startedAt?: string;
            /** @enum {string} */
            status?: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            systemPrompt?: string;
            /** Format: int64 */
            taskId?: number;
            userPrompt?: string;
        };
        ScaffoldEntry: {
            /** @enum {string} */
            outcome?: "CREATED" | "EXISTING";
            path?: string;
        };
        SoftwareChoice: {
            /** @enum {string} */
            availability?: "INSTALLED" | "NOT_INSTALLED" | "WEB" | "RUNNING" | "STOPPED" | "INCOMPATIBLE_HARDWARE" | "UNKNOWN";
            executionTarget?: boolean;
            key?: string;
            launchable?: boolean;
            name?: string;
            reason?: string;
        };
        SoftwareRequest: {
            appId?: string;
            capabilities?: string[];
            /** @enum {string} */
            category: "AGENTIC_IDE" | "IDE" | "EDITOR" | "TERMINAL" | "AI_CLOUD" | "AI_LOCAL" | "DATABASE" | "API" | "INFRASTRUCTURE" | "DIAGRAM" | "DESIGN" | "THREE_D" | "VCS" | "HOSTING" | "PRODUCTIVITY";
            cliCommand?: string;
            configuration?: string;
            embedNote?: string;
            embeddable?: boolean;
            enabled?: boolean;
            executable?: string;
            executableArgs?: string[];
            executionTarget?: boolean;
            healthUrl?: string;
            iconUrl?: string;
            incompatibleReason?: string;
            key?: string;
            /** @enum {string} */
            launchKind: "DESKTOP" | "CLI" | "WEB" | "LOCAL_SERVICE";
            name: string;
            openFolder?: boolean;
            projectTypes?: string[];
            purpose?: string;
            requirements?: string;
            role: string;
            url?: string;
        };
        SoftwareResponse: {
            appId?: string;
            /** @enum {string} */
            availability?: "INSTALLED" | "NOT_INSTALLED" | "WEB" | "RUNNING" | "STOPPED" | "INCOMPATIBLE_HARDWARE" | "UNKNOWN";
            availabilityDetail?: string;
            capabilities?: string[];
            /** @enum {string} */
            category?: "AGENTIC_IDE" | "IDE" | "EDITOR" | "TERMINAL" | "AI_CLOUD" | "AI_LOCAL" | "DATABASE" | "API" | "INFRASTRUCTURE" | "DIAGRAM" | "DESIGN" | "THREE_D" | "VCS" | "HOSTING" | "PRODUCTIVITY";
            cliCommand?: string;
            configuration?: string;
            /** Format: date-time */
            createdAt?: string;
            embedNote?: string;
            embeddable?: boolean;
            enabled?: boolean;
            executable?: string;
            executableArgs?: string[];
            executionTarget?: boolean;
            healthUrl?: string;
            iconUrl?: string;
            /** Format: int64 */
            id?: number;
            incompatibleReason?: string;
            key?: string;
            /** @enum {string} */
            launchKind?: "DESKTOP" | "CLI" | "WEB" | "LOCAL_SERVICE";
            launchable?: boolean;
            name?: string;
            openFolder?: boolean;
            projectTypes?: string[];
            purpose?: string;
            requirements?: string;
            resolvedExecutable?: string;
            role?: string;
            /** Format: date-time */
            updatedAt?: string;
            url?: string;
            /** Format: int64 */
            version?: number;
        };
        Suggestion: {
            /** Format: int64 */
            agentId?: number;
            matchedTerms?: string[];
            model?: string;
            name?: string;
            role?: string;
            /** Format: int32 */
            score?: number;
            specialization?: string;
        };
        Target: {
            available?: boolean;
            detail?: string;
            key?: string;
            /** @enum {string} */
            kind?: "ENGINE" | "CLI" | "DESKTOP" | "MANUAL";
            name?: string;
        };
        TaskAgentAssignmentRequest: {
            /** Format: int64 */
            agentId: number;
        };
        TaskCreateRequest: {
            /** Format: int64 */
            agentId?: number;
            description?: string;
            priority: string;
            /** Format: int64 */
            projectId?: number;
            status: string;
            title: string;
        };
        TaskProjectAssignmentRequest: {
            /** Format: int64 */
            projectId: number;
        };
        TaskResponse: {
            /** Format: int64 */
            agentId?: number;
            code?: string;
            description?: string;
            documentPath?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            phaseId?: number;
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH";
            /** Format: int64 */
            projectId?: number;
            /** @enum {string} */
            status?: "OPEN" | "IN_PROGRESS" | "DONE";
            title?: string;
        };
        TaskUpdateRequest: {
            description?: string;
            priority: string;
            title: string;
        };
        UncataloguedModel: {
            available?: boolean;
            billed?: boolean;
            key?: string;
            provider?: string;
        };
        UsageWindowResponse: {
            byModel?: components["schemas"]["ModelTokens"][];
            detail?: string;
            key?: string;
            limitNote?: string;
            name?: string;
            /** Format: date-time */
            nextResetAt?: string;
            /** Format: date-time */
            observedAt?: string;
            /** Format: int64 */
            outputTokens?: number;
            resetTime?: string;
            /** Format: int32 */
            resetWeekday?: number;
            resetZone?: string;
            /** @enum {string} */
            source?: "CODEX_LOCAL" | "CLAUDE_CODE_LOCAL" | "ENGINE_RUNS" | "MANUAL";
            /** @enum {string} */
            status?: "MEASURED" | "COUNTED" | "RESET_SINCE_OBSERVATION" | "NO_DATA" | "CONFIGURATION_NEEDED";
            subject?: string;
            /** Format: int64 */
            tokens?: number;
            usageUrl?: string;
            /** Format: double */
            usedPercent?: number;
            /** Format: int64 */
            version?: number;
            /** @enum {string} */
            windowKind?: "ROLLING_5H" | "DAILY" | "WEEKLY" | "MONTHLY";
            /** Format: date-time */
            windowStart?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAgents: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"][];
                };
            };
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    tasksOfAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    activateAgent: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    deactivateAgent: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelCatalogResponse"];
                };
            };
        };
    };
    classify: {
        parameters: {
            query: {
                key: string;
            };
            header?: {
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelClassificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelResponse"];
                };
            };
        };
    };
    projectTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectTypeInfo"][];
                };
            };
        };
    };
    providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProviderResponse"][];
                };
            };
        };
    };
    models_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModelList"];
                };
            };
        };
    };
    approvePhase: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                phaseId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PhaseResponse"];
                };
            };
        };
    };
    requestChanges: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                phaseId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PhaseResponse"];
                };
            };
        };
    };
    run_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanRunResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    documents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Documents"];
                };
            };
        };
    };
    read: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    write: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentWrite"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Document"];
                };
            };
        };
    };
    plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanResponse"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: {
                approveAllPhases?: boolean;
            };
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanRunResponse"];
                };
            };
        };
    };
    handoff_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    importPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanRunResponse"];
                };
            };
        };
    };
    configure: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    scaffold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScaffoldEntry"][];
                };
            };
        };
    };
    tasksOfProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    suggest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Suggestion"][];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SoftwareResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoftwareRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SoftwareResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SoftwareResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoftwareRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SoftwareResponse"];
                };
            };
        };
    };
    icon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    launch_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LaunchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LaunchResponse"];
                };
            };
        };
    };
    getTasks: {
        parameters: {
            query?: {
                status?: "OPEN" | "IN_PROGRESS" | "DONE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"][];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    assignToAgent: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskAgentAssignmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    suggestionsFor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Suggestion"][];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    handoffs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HandoffResponse"][];
                };
            };
        };
    };
    handoff: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HandoffResult"];
                };
            };
        };
    };
    decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Orchestration"];
                };
            };
        };
    };
    assignToProject: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskProjectAssignmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    reopen: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    reviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewResponse"][];
                };
            };
        };
    };
    review: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewResult"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    runsOfTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunResponse"][];
                };
            };
        };
    };
    launch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsageWindowResponse"][];
                };
            };
        };
    };
    anchor: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuotaAnchorRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    defaultFolder: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
