-- PHASE 8 (ADR-018, ADR-019). The Software Hub catalog.
--
-- Purely additive: one new table, nothing existing is touched.
--
-- A row says what a program is for and HOW TO RECOGNISE AND OPEN it on this
-- machine. It never says whether the program is installed: that is detected at
-- read time (ADR-018 §5), because a stored "installed" becomes false the day the
-- program is removed.
--
-- The catalog entries themselves are reference data inserted at startup from
-- classpath:catalog/software.json, only for keys that do not exist yet, so an
-- entry the operator edited is never overwritten (ADR-018 §4).

CREATE TABLE software (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key               VARCHAR(64)   NOT NULL,
    name              VARCHAR(120)  NOT NULL,
    category          VARCHAR(32)   NOT NULL,
    role              VARCHAR(200)  NOT NULL,
    purpose           VARCHAR(1000),
    -- Lower-case tags, comma separated ("java,spring,rest-client"). What the
    -- orchestrator matches a task against.
    capabilities      VARCHAR(1000) NOT NULL DEFAULT '',
    project_types     VARCHAR(500)  NOT NULL DEFAULT '',
    launch_kind       VARCHAR(16)   NOT NULL,
    -- The Windows Start-menu AppID: one launch mechanism for Win32 and Store apps.
    app_id            VARCHAR(300),
    -- An executable path with %ENV% placeholders; one '*' is allowed in a path
    -- segment so that a versioned install folder is still found after an update.
    executable        VARCHAR(500),
    -- Fixed arguments, one per line. Fixed: they come from the catalog, never
    -- from a request (ADR-019 I2).
    executable_args   VARCHAR(1000),
    -- True when the executable accepts one project folder as its argument.
    open_folder       BOOLEAN       NOT NULL DEFAULT FALSE,
    -- For CLI entries: the command run inside Windows Terminal.
    cli_command       VARCHAR(200),
    url               VARCHAR(500),
    health_url        VARCHAR(500),
    embeddable        BOOLEAN       NOT NULL DEFAULT FALSE,
    embed_note        VARCHAR(500),
    -- True for the tools the Master Orchestrator can hand a task to.
    execution_target  BOOLEAN       NOT NULL DEFAULT FALSE,
    requirements      VARCHAR(1000),
    configuration     VARCHAR(1000),
    icon_url          VARCHAR(500),
    -- A known hardware incompatibility, stated instead of detected (DwarfStar4).
    incompatible_reason VARCHAR(500),
    enabled           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    version           BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT software_key_format CHECK (key ~ '^[a-z0-9][a-z0-9-]{1,63}$'),
    CONSTRAINT software_category_check CHECK (category IN (
        'AGENTIC_IDE', 'IDE', 'EDITOR', 'TERMINAL', 'AI_CLOUD', 'AI_LOCAL', 'DATABASE', 'API',
        'INFRASTRUCTURE', 'DIAGRAM', 'DESIGN', 'THREE_D', 'VCS', 'HOSTING', 'PRODUCTIVITY')),
    CONSTRAINT software_launch_kind_check CHECK (launch_kind IN ('DESKTOP', 'CLI', 'WEB', 'LOCAL_SERVICE')),
    -- Every kind carries what it needs to be opened; a row that cannot be opened
    -- is refused rather than shown with a button that fails.
    CONSTRAINT software_launch_target_check CHECK (
        (launch_kind = 'DESKTOP' AND (app_id IS NOT NULL OR executable IS NOT NULL))
        OR (launch_kind = 'CLI' AND cli_command IS NOT NULL)
        OR (launch_kind = 'WEB' AND url IS NOT NULL)
        OR (launch_kind = 'LOCAL_SERVICE' AND url IS NOT NULL))
);

CREATE UNIQUE INDEX software_key_unique_idx ON software (key);
CREATE INDEX software_category_idx ON software (category);
