-- PHASE 8 (ADR-018 §2). Providers and models as two catalogs, and the quota
-- windows the usage view measures against.
--
-- Additive: three new tables. agents.model (V11) stays a 'provider:model'
-- string: the catalog makes it resolvable, it does not become a foreign key --
-- a model the engine knows but nobody catalogued must stay usable.

CREATE TABLE model_providers (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key             VARCHAR(40)   NOT NULL,
    name            VARCHAR(120)  NOT NULL,
    kind            VARCHAR(16)   NOT NULL,
    -- The provider's name inside the AI Engine ('ollama', 'anthropic',
    -- 'openrouter', 'echo'), or NULL when the engine does not serve it.
    engine_provider VARCHAR(40),
    billing         VARCHAR(16)   NOT NULL,
    status          VARCHAR(24)   NOT NULL,
    base_url        VARCHAR(500),
    docs_url        VARCHAR(500),
    notes           VARCHAR(2000),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT model_providers_key_format CHECK (key ~ '^[a-z0-9][a-z0-9-]{1,39}$'),
    CONSTRAINT model_providers_kind_check CHECK (kind IN ('LOCAL', 'CLOUD_API', 'ROUTER', 'SUBSCRIPTION', 'TEST')),
    CONSTRAINT model_providers_billing_check CHECK (billing IN ('FREE', 'PAY_PER_TOKEN', 'SUBSCRIPTION')),
    CONSTRAINT model_providers_status_check CHECK (status IN ('ENABLED', 'DISABLED', 'INCOMPATIBLE_HARDWARE'))
);
CREATE UNIQUE INDEX model_providers_key_unique_idx ON model_providers (key);

CREATE TABLE llm_models (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The engine identifier, 'provider:model' -- the same string agents.model holds.
    key             VARCHAR(200)  NOT NULL,
    provider_key    VARCHAR(40)   NOT NULL REFERENCES model_providers (key),
    display_name    VARCHAR(120)  NOT NULL,
    role            VARCHAR(16)   NOT NULL,
    capabilities    VARCHAR(500)  NOT NULL DEFAULT '',
    context_window  INTEGER,
    size_gb         NUMERIC(7, 1),
    parameters      VARCHAR(20),
    lifecycle       VARCHAR(16)   NOT NULL,
    replaced_by     VARCHAR(200),
    notes           VARCHAR(2000),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT llm_models_key_format CHECK (key ~ '^[a-z0-9-]+:.+$'),
    CONSTRAINT llm_models_role_check CHECK (role IN (
        'FAST', 'GENERAL', 'CODER', 'PLANNER', 'VISION', 'REASONING', 'PREMIUM', 'EMBEDDING', 'TEST')),
    -- CANDIDATE: a proposed replacement not yet verified. The migration rule of
    -- the directive (inventory, role, candidate, verify, migrate, then retire)
    -- is visible in the data instead of only in a document.
    CONSTRAINT llm_models_lifecycle_check CHECK (lifecycle IN ('ACTIVE', 'CANDIDATE', 'DEPRECATED', 'RETIRED'))
);
CREATE UNIQUE INDEX llm_models_key_unique_idx ON llm_models (key);

CREATE TABLE quota_plans (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key             VARCHAR(64)   NOT NULL,
    name            VARCHAR(120)  NOT NULL,
    -- Who the window belongs to: a provider key, or a tool ('claude-code', 'codex').
    subject         VARCHAR(64)   NOT NULL,
    -- Where the usage figure comes from. MANUAL means nobody can measure it and
    -- the view says so instead of showing a number.
    source          VARCHAR(24)   NOT NULL,
    window_kind     VARCHAR(16)   NOT NULL,
    -- For WEEKLY: ISO day of week (1 = Monday) and local time of the reset.
    -- For DAILY: the time only. NULL when the source measures the reset itself.
    reset_weekday   INTEGER,
    reset_time      TIME,
    reset_zone      VARCHAR(64),
    limit_note      VARCHAR(500),
    usage_url       VARCHAR(500),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT quota_plans_key_format CHECK (key ~ '^[a-z0-9][a-z0-9-]{1,63}$'),
    CONSTRAINT quota_plans_source_check CHECK (source IN ('CODEX_LOCAL', 'CLAUDE_CODE_LOCAL', 'ENGINE_RUNS', 'MANUAL')),
    CONSTRAINT quota_plans_window_check CHECK (window_kind IN ('ROLLING_5H', 'DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT quota_plans_weekday_check CHECK (reset_weekday IS NULL OR reset_weekday BETWEEN 1 AND 7)
);
CREATE UNIQUE INDEX quota_plans_key_unique_idx ON quota_plans (key);
