-- PHASE 10 (ADR-021). The implementation plan in the database: the index of the
-- files that hold it (ADR-020).
--
-- Additive: two new tables and three nullable columns on tasks. Every existing
-- task keeps phase_id, code and document_path NULL -- it was created outside a
-- plan, and nothing invents a phase for it. The Human-in-the-Loop gate ("a task
-- of an unapproved phase does not start") therefore never touches them.

CREATE TABLE project_phases (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT        NOT NULL REFERENCES projects (id),
    number          INTEGER       NOT NULL,
    title           VARCHAR(200)  NOT NULL,
    objective       VARCHAR(4000),
    status          VARCHAR(16)   NOT NULL DEFAULT 'PLANNED',
    approval        VARCHAR(24)   NOT NULL DEFAULT 'PENDING',
    approval_note   VARCHAR(2000),
    approved_at     TIMESTAMP WITH TIME ZONE,
    document_path   VARCHAR(500)  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT project_phases_number_positive CHECK (number > 0),
    CONSTRAINT project_phases_status_check CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT project_phases_approval_check CHECK (approval IN ('PENDING', 'APPROVED', 'CHANGES_REQUESTED')),
    -- An approval carries its moment; nothing else does.
    CONSTRAINT project_phases_approved_at_check CHECK ((approval = 'APPROVED') = (approved_at IS NOT NULL))
);
CREATE UNIQUE INDEX project_phases_project_number_idx ON project_phases (project_id, number);

ALTER TABLE tasks ADD COLUMN phase_id      BIGINT REFERENCES project_phases (id);
ALTER TABLE tasks ADD COLUMN code          VARCHAR(16);
ALTER TABLE tasks ADD COLUMN document_path VARCHAR(500);

CREATE INDEX tasks_phase_id_idx ON tasks (phase_id);
-- TASK-NNN is unique inside a project; tasks outside a plan have no code.
CREATE UNIQUE INDEX tasks_project_code_idx ON tasks (project_id, code) WHERE code IS NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT tasks_code_format CHECK (code IS NULL OR code ~ '^TASK-[0-9]{3,5}$');

-- A plan generation or import, and its outcome: the orchestrator's own record,
-- the counterpart of task_runs for the planning step.
CREATE TABLE plan_runs (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT        NOT NULL REFERENCES projects (id),
    source          VARCHAR(16)   NOT NULL,
    status          VARCHAR(16)   NOT NULL,
    requested_model VARCHAR(200),
    served_model    VARCHAR(200),
    output          TEXT,
    failure_detail  VARCHAR(4000),
    phases          INTEGER,
    tasks           INTEGER,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    requested_by    VARCHAR(120)  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at     TIMESTAMP WITH TIME ZONE,

    CONSTRAINT plan_runs_source_check CHECK (source IN ('ENGINE', 'IMPORT')),
    CONSTRAINT plan_runs_status_check CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT plan_runs_outcome_check CHECK (
        (status = 'RUNNING' AND finished_at IS NULL)
        OR (status = 'SUCCEEDED' AND finished_at IS NOT NULL AND phases IS NOT NULL)
        OR (status = 'FAILED' AND finished_at IS NOT NULL AND failure_detail IS NOT NULL))
);
CREATE INDEX plan_runs_project_idx ON plan_runs (project_id, id DESC);
-- At most one planning in flight per project.
CREATE UNIQUE INDEX plan_runs_one_running_idx ON plan_runs (project_id) WHERE status = 'RUNNING';
