-- PHASE 11 (ADR-021 §4-5, ADR-022). Two append-only records of the execution
-- half of the Master Orchestrator: what was handed to an external agent, and
-- what the operator decided about an outcome. Additive: two new tables.

CREATE TABLE task_handoffs (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         BIGINT        NOT NULL REFERENCES tasks (id),
    target          VARCHAR(64)   NOT NULL,
    document_path   VARCHAR(500)  NOT NULL,
    prompt          VARCHAR(2000) NOT NULL,
    command         VARCHAR(4000),
    requested_by    VARCHAR(120)  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX task_handoffs_task_idx ON task_handoffs (task_id, id DESC);

CREATE TABLE task_reviews (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         BIGINT        NOT NULL REFERENCES tasks (id),
    verdict         VARCHAR(24)   NOT NULL,
    note            VARCHAR(4000),
    run_id          BIGINT        REFERENCES task_runs (id),
    handoff_id      BIGINT        REFERENCES task_handoffs (id),
    reviewer        VARCHAR(120)  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT task_reviews_verdict_check CHECK (verdict IN ('ACCEPTED', 'CHANGES_REQUESTED'))
);
CREATE INDEX task_reviews_task_idx ON task_reviews (task_id, id DESC);
