-- PHASE 12 (ADR-023). The agent ecosystem: prompt engineering, sub-agents and
-- the harness, as the directive's sections 13-15 describe them.
--
-- Additive. Every new agents column is nullable: an agent created before this
-- migration has no profile, and its runs keep sending exactly the prompt they
-- sent before (ADR-021 §6 regression).

-- Prompt engineering (directive §13) and the agent's place in the hierarchy (§15).
ALTER TABLE agents ADD COLUMN parent_id        BIGINT REFERENCES agents (id);
ALTER TABLE agents ADD COLUMN domain           VARCHAR(120);
ALTER TABLE agents ADD COLUMN system_prompt    VARCHAR(8000);
ALTER TABLE agents ADD COLUMN responsibilities VARCHAR(4000);
ALTER TABLE agents ADD COLUMN limits           VARCHAR(4000);
ALTER TABLE agents ADD COLUMN output_format    VARCHAR(2000);
-- Directives (§14): one per line, in the order they apply.
ALTER TABLE agents ADD COLUMN directives       VARCHAR(8000);
ALTER TABLE agents ADD COLUMN context_policy   VARCHAR(2000);

-- An agent is not its own ancestor. Deeper cycles are refused by the service,
-- under the lock of the agent being moved.
ALTER TABLE agents ADD CONSTRAINT agents_parent_not_self CHECK (parent_id IS NULL OR parent_id <> id);
CREATE INDEX agents_parent_idx ON agents (parent_id);

-- The harness catalog (ADR-018 §3): skills, knowledge, MCP servers, tools, and
-- the explorer's frameworks and template providers. One table, a closed kind.
CREATE TABLE harness_resources (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key             VARCHAR(64)   NOT NULL,
    kind            VARCHAR(24)   NOT NULL,
    name            VARCHAR(120)  NOT NULL,
    description     VARCHAR(2000),
    tags            VARCHAR(500)  NOT NULL DEFAULT '',
    source_url      VARCHAR(500),
    -- For TEMPLATE_PROVIDER: a URL with {q} where the search terms go.
    search_url      VARCHAR(500),
    -- For MCP and TOOL: how it is configured or invoked, as text.
    configuration   VARCHAR(4000),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT harness_resources_key_format CHECK (key ~ '^[a-z0-9][a-z0-9-]{1,63}$'),
    CONSTRAINT harness_resources_kind_check CHECK (kind IN (
        'SKILL', 'KNOWLEDGE', 'MCP', 'TOOL', 'FRAMEWORK', 'TEMPLATE_PROVIDER'))
);
CREATE UNIQUE INDEX harness_resources_key_unique_idx ON harness_resources (key);

-- What an agent is equipped with, and which software it may use.
CREATE TABLE agent_resources (
    agent_id    BIGINT NOT NULL REFERENCES agents (id),
    resource_id BIGINT NOT NULL REFERENCES harness_resources (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (agent_id, resource_id)
);

CREATE TABLE agent_software (
    agent_id    BIGINT NOT NULL REFERENCES agents (id),
    software_id BIGINT NOT NULL REFERENCES software (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (agent_id, software_id)
);

-- Frameworks, skills or knowledge adopted by a project (the explorer's "install").
CREATE TABLE project_resources (
    project_id  BIGINT NOT NULL REFERENCES projects (id),
    resource_id BIGINT NOT NULL REFERENCES harness_resources (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, resource_id)
);
