-- PHASE 13 (directive §18). Daily Work: what the operator does today, tomorrow,
-- on a given day -- personal items, or references to project tasks. A reference
-- is a foreign key, never a copy: the task's title and status are read from the
-- task, so the two cannot disagree. Additive: one new table.

CREATE TABLE daily_items (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day         DATE          NOT NULL,
    title       VARCHAR(255),
    notes       VARCHAR(2000),
    status      VARCHAR(16)   NOT NULL DEFAULT 'TODO',
    priority    VARCHAR(16)   NOT NULL DEFAULT 'MEDIUM',
    due_time    TIME,
    task_id     BIGINT        REFERENCES tasks (id),
    position    INTEGER       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT daily_items_status_check CHECK (status IN ('TODO', 'DOING', 'DONE')),
    CONSTRAINT daily_items_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    -- A personal item has a title; a reference takes the task's.
    CONSTRAINT daily_items_title_or_task CHECK (title IS NOT NULL OR task_id IS NOT NULL)
);
CREATE INDEX daily_items_day_idx ON daily_items (day, position);
CREATE INDEX daily_items_task_idx ON daily_items (task_id);
