-- Initial schema for AI Company OS.
--
-- This migration creates the schema from scratch on an empty PostgreSQL
-- database. It is deliberately NOT a baseline of the previous Hibernate
-- generated H2 schema: types, identity generation and constraints are chosen
-- for PostgreSQL and are the reference the entities are validated against.

CREATE TABLE agents (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    role           VARCHAR(255) NOT NULL,
    specialization VARCHAR(255) NOT NULL,
    active         BOOLEAN      NOT NULL
);

CREATE TABLE tasks (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(5000),
    status      VARCHAR(255) NOT NULL,
    priority    VARCHAR(255) NOT NULL
);
