-- Project registry: the first real domain of the Company OS.
--
-- A project is the logical container that tasks, agents, documents, frameworks,
-- templates, integrations and memory will eventually hang from. This migration
-- creates the container only: no existing table is touched and no foreign key is
-- introduced yet, so V2 is additive and cannot disturb agents or tasks.
--
-- Projects are never deleted physically by the application. The lifecycle ends in
-- ARCHIVED, which is why there is no ON DELETE behaviour to design here.

CREATE TABLE projects (
    id          BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120)             NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(32)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

    -- The allowed set is closed and owned by the database, not only by the enum:
    -- a row written outside the application cannot introduce a status the domain
    -- does not know how to interpret. Widening the set requires a migration.
    CONSTRAINT projects_status_check CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

-- A registry needs stable, unambiguous names. Uniqueness is case insensitive so
-- "Company OS" and "company os" cannot coexist, and it is enforced here rather
-- than only in the service: a concurrent create must not be able to slip past it.
CREATE UNIQUE INDEX projects_name_unique_idx ON projects (lower(name));

-- Listing a registry is nearly always scoped by lifecycle state.
CREATE INDEX projects_status_idx ON projects (status);
